Landing page
masraniJay/E-commerece-site pull request #1
Opened 2022-02-17 18:50 UTC by masraniJay

Added landing page.

2022-02-17 19:03 UTC, anurag-kkumarr requested changes
It looks good

2022-02-17 19:04 UTC, dusariudaykumar approved these changes
looks good

2022-02-18 06:22 UTC, shubhmehra commented on index.html
> +            <a href="" class="navigation-item">Cart</a>
why empty hrefs?

2022-02-18 06:23 UTC, shubhmehra commented on index.html
> +                <img class="card-image" src="assets/kidswear.jpg">
please use alt tags for better accessiblity

2022-02-18 06:23 UTC, shubhmehra commented on index.html
> +</html>
code formatting need to

2022-02-18 06:25 UTC, shubhmehra approved these changes
please use prettier for code formatting
otherwise looks good

2022-02-19 11:24 UTC, merged